repos:
  - repo: 'https://github.com/pre-commit/pre-commit-hooks'
    rev: v5.0.0
    hooks:
      - id: check-added-large-files
      - id: check-json
      - id: pretty-format-json
        args: ['--no-sort-keys', '--no-ensure-ascii', '--autofix']
      - id: check-merge-conflict
      - id: check-xml
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: 'https://github.com/Lucas-C/pre-commit-hooks-lxml'
    rev: v1.1.0
    hooks:
      - id: forbid-html-img-without-alt-text
